TOPDIR=./../../..

TARGET=Smoother

TARGET_EXEPATH=$(TOPDIR)/bin

INCLUDE_PATH=$(TOPDIR)/include
CFLAGS+=-I$(INCLUDE_PATH)

LDFLAGS+=-L$(TOPDIR)/lib
LIBS_DEPEND+=-lGLTools -lGLEW -lglut -lGL

include $(TOPDIR)/Makefile.env
