TOPDIR=./../..

LIB=libGLTools.so

TARGET_LIBPATH=$(TOPDIR)/lib

INCLUDE_PATH=$(TOPDIR)/include
CFLAGS+=-fpic
CFLAGS+=-I$(INCLUDE_PATH)

LDFLAGS+=
LIBS_DEPEND+=-lGLEW -lGL

include $(TOPDIR)/Makefile.env
