TOPDIR=./..

exclude_dirs=Chapter01 \
			 Chapter02 \
			 Chapter04 \
			 Chapter05 \
			 Chapter06 \
			 Chapter07 \
			 Chapter08 \
			 Chapter09 \
			 Chapter10 \
			 Chapter11 \
			 Chapter12 \
			 Chapter13 \
			 Chapter15 \
			 GLTools \

include $(TOPDIR)/Makefile.env
